
## Turn on away mode if everyone is NOT HOME
- alias: "Enable Away Mode on NOT HOME"
  trigger:
     platform: state
     entity_id: group.all_devices
     to: 'not_home'
  action:
     service: input_boolean.turn_on
     entity_id: input_boolean.enable_away

## Turn off away mode if everyone is HOME
- alias: "Disable Away Mode on HOME"
  trigger:
     platform: state
     entity_id: group.all_devices
     to: 'home'
  action:
     service: input_boolean.turn_off
     entity_id: input_boolean.enable_away

## Lights off on Away Mode
- alias: "Turn off all lights on Away mode"
  trigger:
     platform: state
     entity_id: input_boolean.enable_away
     to: 'on'
  action:
     service: light.turn_off
     entity_id: group.all_lights
