
## Play None
- alias: Kitchen - Play None
  trigger:
    platform: state
    entity_id: input_select.kitchen_watch_type
    to: "None"
  action:
    service: script.turn_on
    data:
      entity_id: script.kitchen_daydream_script

#--------------
# Media Player
#--------------
-  alias: Kitchen - Play When Ready
   initial_state: False
   trigger:
      platform: state
      entity_id: media_player.kitchen
      to: 'idle'
   action:
      service: script.turn_on
      entity_id: script.kitchen_play_kodi      

#--------------
# Webcam feeds
#--------------

## Play Daniel's Room
- alias: Kitchen - Play Daniel's Room
  trigger:
    platform: state
    entity_id: input_select.kitchen_watch_type
    to: "Daniels Room"
  action:
    service: script.turn_on
    data:
      entity_id: script.kitchen_daniel_room_script

## Play Baby's Room
- alias: Kitchen - Play Baby's Room
  trigger:
    platform: state
    entity_id: input_select.kitchen_watch_type
    to: "Baby Room"
  action:
    service: script.turn_on
    data:
      entity_id: script.kitchen_baby_room_script

#--------------
# Youtube feeds
#--------------

## Play ChuChuTV
- alias: Kitchen - Play ChuChuTV
  trigger:
    platform: state
    entity_id: input_select.kitchen_watch_type
    to: "ChuChuTV"
  action:
    service: script.turn_on
    data:
      entity_id: script.kitchen_chuchutv_script

## Play Farmees
- alias: Kitchen - Play Farmees
  trigger:
    platform: state
    entity_id: input_select.kitchen_watch_type
    to: "Farmees"
  action:
    service: script.turn_on
    data:
      entity_id: script.kitchen_farmees_script

## Play Kid's TV
- alias: Kitchen - Play Kid's TV
  trigger:
    platform: state
    entity_id: input_select.kitchen_watch_type
    to: "Kids TV"
  action:
    service: script.turn_on
    data:
      entity_id: script.kitchen_kidstv_script

## Play BBC News
- alias: Kitchen - Play BBC News
  trigger:
    platform: state
    entity_id: input_select.kitchen_watch_type
    to: "BBC News"
  action:
    service: script.turn_on
    data:
      entity_id: script.kitchen_bbc_news_script
      
#--------------
# Web feeds
#--------------
     
## Open Home Assistant
- alias: Kitchen - Open Home Assistant
  trigger:
    platform: state
    entity_id: input_select.kitchen_watch_type
    to: "Home Assistant"
  action:
    service: script.turn_on
    data:
      entity_id: script.kitchen_hass_script
     
## Open Calendar
- alias: Kitchen - Open Calendar
  trigger:
    platform: state
    entity_id: input_select.kitchen_watch_type
    to: "Calendar"
  action:
    service: script.turn_on
    data:
      entity_id: script.kitchen_calendar_script

#--------------
# TTS
#--------------

## Play Weather script
- alias: Kitchen - Play Weather
  trigger:
    platform: state
    entity_id: input_select.kitchen_listen_type
    to: "Weather"
  action:
    service: script.turn_on
    data:
      entity_id: script.kitchen_weather_script

## Play Greeting script
- alias: Kitchen - Play Greeting
  trigger:
    platform: state
    entity_id: input_select.kitchen_listen_type
    to: "Greeting"
  action:
    service: script.turn_on
    data:
      entity_id: script.kitchen_greeting_script
     
## Play House Temp script
- alias: Kitchen - Play Indoor Temps
  trigger:
    platform: state
    entity_id: input_select.kitchen_listen_type
    to: "Temperature"
  action:
    service: script.turn_on
    data:
      entity_id: script.kitchen_hometemp_script

## Play Time script
- alias: Kitchen - Play Time
  trigger:
    platform: state
    entity_id: input_select.kitchen_listen_type
    to: "Time"
  action:
    service: script.turn_on
    data:
      entity_id: script.kitchen_time_script
      
#--------------
# Audio
#--------------

- alias: 'Kitchen - Grandfather Clock'
  initial_state: true
  trigger:
    platform: time
    minutes: 00
    seconds: 00
  condition:
    condition: time
    after: '05:30:00'
    before: '23:30:00'
  action:
    service: media_player.play_media
    data_template:
      entity_id: media_player.kitchen
      media_content_id: '/mnt/shell/emulated/0/GFChime/GrandFatherChime{{ now().strftime("%I") }}.wav'
      media_content_type: 'music'