- alias: "LED Strip Animation Speed"
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: input_slider.led_strip_speed
  action:
    service: mqtt.publish
    data_template:
      topic: "home/led-strip1/set"
      payload: '{"transition":{{ trigger.to_state.state | int }}}'
