
#-----------------
# Brightness
#-----------------

- alias: LED Strip - Set Brightness
  trigger:
    platform: state
    entity_id: input_slider.led_strip
  action:
    service: light.turn_on
    data_template:
      entity_id: light.led_strip
      brightness: '{{ trigger.to_state.state | int }}'

- alias: "LED Strip - Get Brightness"
  trigger:
    platform: numeric_state
    entity_id: light.led_strip
    value_template: "{{ states.light.led_strip.attributes.brightness | int }}"
    above: -1
  action:
    service: input_slider.select_value
    data_template:
       entity_id: input_slider.led_strip
       value: "{{ states.light.led_strip.attributes.brightness | int }}"
      
#-----------------
# Speed
#-----------------

- alias: "LED Strip - Animation Speed"
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: input_slider.led_strip_speed
  action:
    service: mqtt.publish
    data_template:
      topic: "home/led-strip1/set"
      payload: '{"transition":{{ trigger.to_state.state | int }}}'

#-----------------
# Animations
#-----------------

## BPM
- alias: LED Strip - BPM
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "BPM"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: bpm
      
## Candy cane
- alias: LED Strip - Candy cane
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "BPM"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: candy cane

## Confetti
- alias: LED Strip - Confetti
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "Confetti"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: confetti

## Cyclon Rainbow
- alias: LED Strip - Cyclon Rainbow
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "Cyclon Rainbow"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: cyclon rainbow

## Dots
- alias: LED Strip - Dots
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "Dots"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: dots

## Fire
- alias: LED Strip - Fire
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "Fire"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: fire

## Glitter
- alias: LED Strip - Glitter
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "Glitter"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: glitter

## Juggle
- alias: LED Strip - Juggle
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "Juggle"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: juggle

## Lightning
- alias: LED Strip - Lightning
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "Lightning"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: lightning

## Noise
- alias: LED Strip - Noise
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "Noise"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: noise

## Police all
- alias: LED Strip - Police all
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "Police all"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: police all

## Police one
- alias: LED Strip - Police one
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "Police one"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: police one

## Rainbow with Glitter 
- alias: LED Strip - Rainbow with Glitter
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "Rainbow with Glitter"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: rainbow with glitter

## Ripple
- alias: LED Strip - Ripple
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "Ripple"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: ripple

## Sinelon
- alias: LED Strip - Sinelon
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "Sinelon"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: sinelon

## Solid
- alias: LED Strip - Solid
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "Solid"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: solid

## Twinkle
- alias: LED Strip - Twinkle
  trigger:
    platform: state
    entity_id: input_select.led_strip_animation
    to: "Twinkle"
  action:
    service: light.turn_on
    data:
      entity_id: light.led_strip
      effect: twinkle
